-- insert into education

INSERT INTO education.education_place(education_place_name,
                                      education_place_description,
                                      education_place_logo,
                                      education_place_time_interval)
VALUES ('Бакалавриат РТУ МИРЭА',
        'Закончил бакалавриат Российского Технологического Университета по направлению "Информатика и вычислительная техника"',
        'svg',
        '2015-2019'),
       ('Курс по сетям CISCO',
        'Прошел курс по организации сетей от CISCO',
        'svg',
        '2017-2019'),
       ('Магистратура РТУ МИРЭА',
        'Закончил магистратуру Российского Технологического Университета по направлению "Информационные системы и технологии"',
        'svg',
        '2019-2022');

-- insert into career

INSERT INTO career.work_place(work_place_name,
                                 work_place_description,
                                 work_place_logo,
                                 work_place_time_interval)
VALUES ('Моринфорсистема "Агат"',
        'Инженер программист в концерне Моринформсистема "Агат". Занимался разработкой систем для МО РФ на C++ и фреймворке QT',
        'svg',
        '2019-2021'),
       ('Срочная служба в Армии России',
        'Прошел срочную службу в Армии России после окончания магистратуры',
        'svg',
        '2021-2022'),
       ('Акцинерное общество "Управление Административными зданиями"',
        'Работаю по совместительству заместителем руководителя группы сопровождения ИТ процессов и fullstack разработчиком внутренних продуктов компании',
        'svg',
        '2022-н.в');

-- insert into skills

INSERT INTO skills.main_skills(main_skills_name,
                               main_skills_description,
                               main_skills_logo)
VALUES ('Разработка удобных для пользователя интерфейсов',
        'Повышение удобства пользователя при использовании продукта',
        'svg'),
       ('Адаптивные интерфейсы',
        'Навык создания адаптивных интерфейсов для различных устройств обеспечивает оптимальное взаимодействие с пользователем',
        'svg'),
       ('Разработка Full Rest API приложений',
        'Навык разработки как с frontend так и с backend составляющей веб приложений',
        'svg'),
       ('Работа с БД',
        'Навык организации взаимодействия backend веб приложения с базой данных. Создание триггерных функций и написание нативных запросов',
        'svg'),
       ('Тестирование',
        'Навык внедрения интеграционных тестов во время разработки приложения',
        'svg'),
       ('Работа с системой контроля версий',
        'Работа в команде с системой контроля версий GIT',
        'svg');

INSERT INTO skills.frontend_skills(frontend_skills_name,
                                   frontend_skills_description,
                                   frontend_skills_logo)
VALUES ('HTML 5',
        '3+ лет опыта',
        'svg'),
       ('CSS',
        '3+ лет опыта',
        'svg'),
       ('JavaScript',
        '3+ лет опыта',
        'VUE 3'),
       ('3+ лет опыта',
        'Навык организации взаимодействия backend веб приложения с базой данных. Создание триггерных функций и написание нативных запросов',
        'svg'),
       ('QT',
        '3+ лет опыта',
        'svg');

INSERT INTO skills.backend_skills(backend_skills_name,
                                  backend_skills_description,
                                  backend_skills_logo)
VALUES ('Postgre SQL',
        '3+ лет опыта',
        'svg'),
       ('JAVA',
        '3+ лет опыта',
        'svg'),
       ('Node.js',
        '3+ лет опыта',
        'svg'),
       ('Spring Boot',
        '3+ лет опыта',
        'svg'),
       ('Apache Maven',
        '3+ лет опыта',
        'svg'),
       ('С++',
        '3+ лет опыта',
        'svg');

INSERT INTO contacts.user(user_first_name,
                          user_last_name,
                          user_middle_name,
                          user_phone,
                          user_mail,
                          user_git,
                          user_photo_url)
VALUES ('Андрей',
        'Щербаков',
        'Алексеевич',
        '8-916-027-48-62',
        'andrschkit@gmail.com',
        'https://github.com/andrschkit',
        'https://localhost:8080/userphoto.jpg');

INSERT INTO portfolio.product(product_name,
                              product_description,
                              product_logo_img_url,
                              product_img_url,
                              product_link)
VALUES ('Сайт АО "УАЗ"',
        'Сайт компании "Упарвление Административными Зданиям", разработанный командой из 3-х человек ',
        'https://localhost:8080/site_logo.jpg',
        'https://localhost:8080/site.jpg',
        'https://uaz-rosatom.ru/'),
       ('Приложение заявок',
        'Приложение для вывода заявок пользователей и просмотра уже исполненных. Арминистраторы своевременно получают уведомление и могут в реальном времени отслеживать, находящиеся в работе заявки',
        'https://localhost:8080/supplications_logo.jpg',
        'https://localhost:8080/supplications.jpg',
        'https://uaz-rosatom.ru:13101/'),
       ('Приложение склада',
        'Приложение для отслеживания информационно-технического оборудования организации. Внедрена история перемещений и функционал записи оборудования на определенного сотрудника',
        'https://localhost:8080/inventory_logo.jpg',
        'https://localhost:8080/inventory.jpg',
        'https://uaz-rosatom.ru:13100/'),
       ('Бот-сервис в телеграмм для Заявок',
        'Телеграмм бот для создания и просмотра заявок на разные службы организации. У пользователя есть возможность описать проблему, а у администраторов связаться с пользователем, взять в работу или подвердить выполнение заявки',
        'https://localhost:8080/supplications_tg_logo.jpg',
        'https://localhost:8080/supplications_tg.jpg',
        'https://t.me/UAZ_RA_bot'),
       ('Бот-сервис в телеграм для Аварий',
        'Телеграм бот для оповещения пользователец о произошедшей аварии. Создание уведомления просиходит диспетчерами, после подтверждения гралвным инженером авария рассылается необходимым службам',
        'https://localhost:8080/alarms_tg_logo.jpg',
        'https://localhost:8080/alarms_tg.jpg',
        'https://t.me/UAZ_Alarms_RA_bot');