--education

create schema education
    create table education.education_place
    (
        education_place_id int8 generated by default as identity,
        education_place_name varchar(255) not null,
        education_place_description varchar(255),
        education_place_logo varchar(255),
        education_place_time_interval varchar(255),

        constraint education_place_pk primary key (education_place_id)
    );
    alter table education.education_place
        owner to postgres;

--career

create schema career
    create table career.work_place
    (
        work_place_id int8 generated by default as identity,
        work_place_name varchar(255) not null,
        work_place_description varchar(255),
        work_place_logo varchar(255),
        work_place_time_interval varchar(255),

        constraint work_place_pk primary key (work_place_id)
    );
    alter table career.work_place
        owner to postgres;

--skills

create schema skills
    create table skills.main_skills
    (
        main_skills_id int8 generated by default as identity,
        main_skills_name varchar(255) not null,
        main_skills_description varchar(255),
        main_skills_logo varchar(255),

        constraint main_skills_pk primary key (main_skills_id)
    );
    alter table skills.main_skills
        owner to postgres;

    create table skills.frontend_skills
    (
        frontend_skills_id int8 generated by default as identity,
        frontend_skills_name varchar(255) not null,
        frontend_skills_description varchar(255),
        frontend_skills_logo varchar(255),

        constraint frontend_skills_pk primary key (frontend_skills_id)
    );
    alter table skills.frontend_skills
        owner to postgres;

    create table skills.backend_skills
    (
        backend_skills_id int8 generated by default as identity,
        backend_skills_name varchar(255) not null,
        backend_skills_description varchar(255),
        backend_skills_logo varchar(255),

        constraint backend_skills_pk primary key (backend_skills_id)
    );
    alter table skills.backend_skills
        owner to postgres;

--contacts

create schema contacts
    create table contacts.user
    (
        user_id int8 generated by default as identity,
        user_first_name varchar(255) not null,
        user_last_name varchar(255) not null,
        user_middle_name varchar(255),
        user_phone varchar(255),
        user_mail varchar(255),
        user_git varchar(255),
        user_photo_url varchar(255),

        constraint user_pk primary key (user_id)
    );
alter table contacts.user
    owner to postgres;

--portfolio

create schema portfolio
    create table portfolio.product
    (
        product_id int8 generated by default as identity,
        product_name varchar(255) not null,
        product_description varchar(255),
        product_logo_img_url varchar(255),
        product_img_url varchar(255),
        product_link varchar(255),

        constraint product_pk primary key (product_id)
    );
alter table portfolio.product
    owner to postgres;

-- extensions (merged from later migrations; DDL only)

ALTER TABLE contacts."user"
    ADD COLUMN IF NOT EXISTS user_telegram varchar(255),
    ADD COLUMN IF NOT EXISTS user_vk varchar(255);

ALTER TABLE education.education_place
    ADD COLUMN IF NOT EXISTS education_place_certificate_url varchar(512);

ALTER TABLE portfolio.product
    ADD COLUMN IF NOT EXISTS product_nda boolean not null default false,
    ADD COLUMN IF NOT EXISTS product_screenshot_1_url varchar(512),
    ADD COLUMN IF NOT EXISTS product_screenshot_2_url varchar(512);