--education

create schema education
    create table education.education_place
    (
        education_place_id int8 generated by default as identity,
        education_place_name varchar(255) not null,
        education_place_description varchar(255),
        education_place_logo varchar(255),
        education_place_time_interval varchar(255),

        constraint education_place_pk primary key (education_place_id)
    );
    alter table education.education_place
        owner to postgres;

--career

create schema career
    create table career.work_place
    (
        work_place_id int8 generated by default as identity,
        work_place_name varchar(255) not null,
        work_place_description varchar(255),
        work_place_logo varchar(255),
        work_place_time_interval varchar(255),

        constraint work_place_pk primary key (work_place_id)
    );
    alter table career.work_place
        owner to postgres;

--skills

create schema skills
    create table skills.main_skills
    (
        main_skills_id int8 generated by default as identity,
        main_skills_name varchar(255) not null,
        main_skills_description varchar(255),
        main_skills_logo varchar(255),

        constraint main_skills_pk primary key (main_skills_id)
    );
    alter table skills.main_skills
        owner to postgres;

    create table skills.frontend_skills
    (
        frontend_skills_id int8 generated by default as identity,
        frontend_skills_name varchar(255) not null,
        frontend_skills_description varchar(255),
        frontend_skills_logo varchar(255),

        constraint frontend_skills_pk primary key (frontend_skills_id)
    );
    alter table skills.frontend_skills
        owner to postgres;

    create table skills.backend_skills
    (
        backend_skills_id int8 generated by default as identity,
        backend_skills_name varchar(255) not null,
        backend_skills_description varchar(255),
        backend_skills_logo varchar(255),

        constraint backend_skills_pk primary key (backend_skills_id)
    );
    alter table skills.backend_skills
        owner to postgres;

--contacts

create schema contacts
    create table contacts.user
    (
        user_id int8 generated by default as identity,
        user_first_name varchar(255) not null,
        user_last_name varchar(255) not null,
        user_middle_name varchar(255),
        user_phone varchar(255),
        user_mail varchar(255),
        user_git varchar(255),
        user_photo_url varchar(255),

        constraint user_pk primary key (user_id)
    );
alter table contacts.user
    owner to postgres;

--portfolio

create schema portfolio
    create table portfolio.product
    (
        product_id int8 generated by default as identity,
        product_name varchar(255) not null,
        product_description varchar(255),
        product_img_url varchar(255),
        product_link varchar(255),

        constraint product_pk primary key (product_id)
    );
alter table portfolio.product
    owner to postgres;

-- extensions (merged from later migrations; DDL only)

ALTER TABLE contacts."user"
    ADD COLUMN IF NOT EXISTS user_telegram varchar(255),
    ADD COLUMN IF NOT EXISTS user_vk varchar(255);

ALTER TABLE education.education_place
    ADD COLUMN IF NOT EXISTS education_place_certificate_url varchar(512);

ALTER TABLE portfolio.product
    ADD COLUMN IF NOT EXISTS product_nda boolean not null default false,
    ADD COLUMN IF NOT EXISTS product_screenshot_1_url varchar(512),
    ADD COLUMN IF NOT EXISTS product_screenshot_2_url varchar(512);

-- insert into education

INSERT INTO education.education_place(education_place_name,
                                      education_place_description,
                                      education_place_logo,
                                      education_place_time_interval,
                                      education_place_certificate_url)
VALUES ('Бакалавр, МИРЭА',
        'Направление «Информатика и вычислительная техника» (09.03.01)',
        'svg',
        '2015–2019',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/certificates/bakalavr.jpeg'),
       ('Магистр, МИРЭА',
        'Направление «Информационные системы и технологии» (09.04.02)',
        'svg',
        '2019–2021',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/certificates/mag.jpeg'),
       ('Сертификат Cisco',
        'Курс по организации компьютерных сетей',
        'svg',
        '2017–2019',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/certificates/cisco.jpeg'),
       ('Сертификат SAS',
        'Курс по SAS BASE, SAS DS2 Programmer''s Guide',
        'svg',
        '2018',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/certificates/sas.jpeg');

-- insert into career (id по возрастанию: от старых к новым; на фронте — обратный порядок)

INSERT INTO career.work_place(work_place_name,
                              work_place_description,
                              work_place_logo,
                              work_place_time_interval)
VALUES ('Концерн «Моринформсистема-Агат»',
        'Имитаторы систем реального времени на C++ и Qt • Интерфейсы с интеграцией КИП • Командная разработка ПО для МО РФ',
        'svg',
        '2019–2021'),
       ('Вооружённые силы РФ',
        'Срочная служба (рядовой)',
        'svg',
        '2021–2022'),
       ('АО «УАЗ» ГК Росатом — Fullstack',
        'Корпоративный портал (HTML, CSS, Bootstrap, JS): команда 3, 3 мес., 50+ DAU • Учёт оборудования (Spring Boot + PostgreSQL): инвентаризация 4 ч → 20 мин • Прототип системы заявок',
        'svg',
        '2022–2024'),
       ('АО «УАЗ» ГК Росатом — Зам. руководителя',
        'Self-hosted: Mattermost, GitLab (15+ репо), OAuth2 для 5 микросервисов • 3 продукта: монолит → микросервисы, деплой 1 день → 1 ч • Почта/облако на open-source: −30% затрат • Автозаявки TG+email: 70% без 1-й линии',
        'svg',
        '2024–2026'),
       ('АО «УАЗ» ГК Росатом — Начальник отдела',
        'Отдел 8 чел. (админы, DevOps, разработчики) • KPI и документация сервисов: онбординг 2 нед → 3 дня • CI/CD микросервисов: вывод фичи 2 нед → 3 дня',
        'svg',
        '2026–н.в.');

-- insert into skills: main = управление и процессы

INSERT INTO skills.main_skills(main_skills_name,
                               main_skills_description,
                               main_skills_logo)
VALUES ('Управление командами',
        'Отдел до 8 человек: системные администраторы, разработчики, DevOps',
        'svg'),
       ('Agile (Scrum, Kanban)',
        'Управление бэклогом, планирование спринтов и ресурсов',
        'svg'),
       ('KPI и процессы',
        'Постановка KPI, документация сервисов, наставничество',
        'svg'),
       ('Jira / GitLab',
        'Управление проектами, 15+ репозиториев, процессы разработки',
        'svg'),
       ('Docker',
        'docker-compose, контейнеризация и оркестрация микросервисов',
        'svg'),
       ('GitLab CI/CD',
        'Пайплайны автодеплоя: вывод фичи с 2 недель до 3 дней',
        'svg'),
       ('Микросервисная архитектура',
        'Миграция 3 продуктов с монолита: деплой с 1 дня до 1 часа',
        'svg'),
       ('Self-hosting',
        'Mattermost, GitLab, OAuth2 — единая авторизация 5 сервисов',
        'svg'),
       ('Техническое лидерство',
        'От постановки задачи до продакшена: fullstack и инфраструктура',
        'svg');

INSERT INTO skills.frontend_skills(frontend_skills_name,
                                   frontend_skills_description,
                                   frontend_skills_logo)
VALUES ('Vue.js',
        'Pet-проекты и это резюме на Vue 3 + Vite',
        'svg'),
       ('JavaScript',
        'ES6+, REST-клиенты, интерактивные интерфейсы',
        'svg'),
       ('HTML5 / CSS3',
        'Адаптивная вёрстка, корпоративные порталы',
        'svg'),
       ('Bootstrap',
        'Корпоративный портал УАЗ, командная разработка',
        'svg');

INSERT INTO skills.backend_skills(backend_skills_name,
                                  backend_skills_description,
                                  backend_skills_logo)
VALUES ('Java / Spring Boot',
        'REST API, учёт оборудования, бэкенд этого резюме',
        'svg'),
       ('PostgreSQL',
        'Проектирование схем, хранение данных приложений',
        'svg'),
       ('REST API',
        'Проектирование и интеграция микросервисов',
        'svg'),
       ('Docker',
        'Контейнеры, docker-compose, prod- и dev-стенды',
        'svg'),
       ('GitLab CI/CD',
        'Сборка, тесты, автоматический деплой в прод',
        'svg'),
       ('OAuth2',
        'Единый сервер авторизации для микросервисов',
        'svg'),
       ('Linux',
        'Ubuntu, Debian, Astra Linux — администрирование',
        'svg');

INSERT INTO contacts.user(user_first_name,
                          user_last_name,
                          user_middle_name,
                          user_phone,
                          user_mail,
                          user_git,
                          user_photo_url,
                          user_telegram,
                          user_vk)
VALUES ('Андрей',
        'Щербаков',
        'Алексеевич',
        '+7 (916) 027-48-62',
        'andrschkit@gmail.com',
        'https://github.com/andrschkit',
        null,
        'https://t.me/andrschkit',
        'https://vk.com/andrryuk');

INSERT INTO portfolio.product(product_name,
                              product_description,
                              product_img_url,
                              product_link,
                              product_nda,
                              product_screenshot_1_url,
                              product_screenshot_2_url)
VALUES ('Корпоративный портал компании УАЗ',
        'Корпоративный веб-портал для сотрудников и клиентов: разработка в команде из 3 человек, срок реализации 3 месяца, аудитория 50+ уникальных пользователей в день.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/website/main.jpg',
        'https://uaz-rosatom.ru/',
        false,
        null,
        null),
       ('Система обработки заявок',
        'Единая система заявок через Web, Telegram и email: около 70 обращений в месяц, до 70% типовых запросов обрабатываются без участия первой линии поддержки.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/supplications/main.jpg',
        null,
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/supplications/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/supplications/bot.jpg'),
       ('Система учёта оборудования (Legacy)',
        'Внутренний сервис на Spring Boot и PostgreSQL для учёта ИТ-активов: автоматизация сократила еженедельную инвентаризацию с 4 часов до 20 минут.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/inventory/main.jpg',
        null,
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/inventory/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/inventory/edit.jpg'),
       ('SSO-сервер корпоративной авторизации',
        'Сервер единого входа (Single Sign-On) для корпоративных сервисов: централизованная аутентификация пользователей и единая точка контроля доступа.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/SSO/main.jpg',
        'https://t.me/UAZ_RA_bot',
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/SSO/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/SSO/mobile.jpg'),
       ('Микросервис управления пользователями',
        'Отдельный микросервис для управления учётными записями, ролями и профилями пользователей с REST API для интеграции с внутренними системами.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/users/main.jpg',
        null,
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/users/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/users/edit_user.jpg'),
       ('Инфраструктура GitLab и CI/CD',
        'Развёрнут и поддерживается self-hosted GitLab: более 15 репозиториев, автоматические пайплайны сборки и деплой микросервисов.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/gitlab/main.jpg',
        null,
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/gitlab/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/gitlab/ci.jpg'),
       ('Корпоративный мессенджер Mattermost',
        'Self-hosted Mattermost для командного взаимодействия: интеграция уведомлений из GitLab и подключение 18 пользователей из разных подразделений.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/mattermost/main.jpg',
        null,
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/mattermost/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/mattermost/devs.jpg'),
       ('Корпоративная почтовая система',
        'Self-hosted почтовая инфраструктура на базе Mailcow и веб-клиента SOGo: централизованная корпоративная почта и календари.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/mail/main.jpg',
        null,
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/mail/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/mail/calendar.jpg'),
       ('Корпоративное облако Nextcloud',
        'Self-hosted облачное хранилище на Nextcloud с интеграцией OnlyOffice для совместной работы с документами внутри компании.',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/nextcloud/main.jpg',
        null,
        true,
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/nextcloud/main.jpg',
        'https://cdn.jsdelivr.net/gh/andrschkit/resume_assets@main/projects/nextcloud/onlyoffice.jpg')
