-- Обновление демо-данных резюме (перезапись seed)

TRUNCATE TABLE
    portfolio.product,
    contacts."user",
    skills.backend_skills,
    skills.frontend_skills,
    skills.main_skills,
    career.work_place,
    education.education_place
RESTART IDENTITY;

INSERT INTO education.education_place(education_place_name,
                                      education_place_description,
                                      education_place_logo,
                                      education_place_time_interval)
VALUES ('Бакалавр, МИРЭА',
        'Направление «Информатика и вычислительная техника» (09.03.01)',
        'svg',
        '2015–2019'),
       ('Магистр, МИРЭА',
        'Направление «Информационные системы и технологии» (09.04.02)',
        'svg',
        '2019–2021'),
       ('Сертификат Cisco',
        'Курс по организации компьютерных сетей',
        'svg',
        '2017–2019');

INSERT INTO career.work_place(work_place_name,
                              work_place_description,
                              work_place_logo,
                              work_place_time_interval)
VALUES ('Концерн «Моринформсистема-Агат»',
        'Имитаторы систем реального времени на C++ и Qt • Интерфейсы с интеграцией КИП • Командная разработка ПО для МО РФ',
        'svg',
        '2019–2021'),
       ('Вооружённые силы РФ',
        'Срочная служба (рядовой)',
        'svg',
        '2021–2022'),
       ('АО «УАЗ» ГК Росатом — Fullstack',
        'Корпоративный портал (HTML, CSS, Bootstrap, JS): команда 3, 3 мес., 50+ DAU • Учёт оборудования (Spring Boot + PostgreSQL): инвентаризация 4 ч → 20 мин • Прототип системы заявок',
        'svg',
        '2022–2024'),
       ('АО «УАЗ» ГК Росатом — Зам. руководителя',
        'Self-hosted: Mattermost, GitLab (15+ репо), OAuth2 для 5 микросервисов • 3 продукта: монолит → микросервисы, деплой 1 день → 1 ч • Почта/облако: −30% затрат • Автозаявки TG+email: 70% без 1-й линии',
        'svg',
        '2024–2026'),
       ('АО «УАЗ» ГК Росатом — Начальник отдела',
        'Отдел 8 чел. (админы, DevOps, разработчики) • KPI и документация сервисов: онбординг 2 нед → 3 дня • CI/CD микросервисов: вывод фичи 2 нед → 3 дня',
        'svg',
        '2026–н.в.');

INSERT INTO skills.main_skills(main_skills_name,
                               main_skills_description,
                               main_skills_logo)
VALUES ('Управление командой',
        'Руководство отделом до 8 человек: админы, разработчики, DevOps',
        'svg'),
       ('Agile',
        'Scrum, Kanban, управление бэклогом, планирование спринтов',
        'svg'),
       ('KPI и процессы',
        'Постановка KPI, документация сервисов, наставничество',
        'svg'),
       ('CI/CD',
        'GitLab CI/CD, docker-compose, автодеплой микросервисов',
        'svg'),
       ('Self-hosting',
        'Mattermost, GitLab, OAuth2 — единая авторизация 5 сервисов',
        'svg'),
       ('Техническое лидерство',
        'От постановки задачи до продакшена: fullstack и инфраструктура',
        'svg');

INSERT INTO skills.frontend_skills(frontend_skills_name,
                                   frontend_skills_description,
                                   frontend_skills_logo)
VALUES ('Vue.js',
        'Pet-проекты и это резюме на Vue 3 + Vite',
        'svg'),
       ('JavaScript',
        'ES6+, REST-клиенты, интерактивные интерфейсы',
        'svg'),
       ('HTML5 / CSS3',
        'Адаптивная вёрстка, корпоративные порталы',
        'svg'),
       ('Bootstrap',
        'Корпоративный портал УАЗ, командная разработка',
        'svg');

INSERT INTO skills.backend_skills(backend_skills_name,
                                  backend_skills_description,
                                  backend_skills_logo)
VALUES ('Java / Spring Boot',
        'REST API, учёт оборудования, бэкенд этого резюме',
        'svg'),
       ('PostgreSQL',
        'Проектирование схем, хранение данных приложений',
        'svg'),
       ('Docker',
        'docker-compose, контейнеризация микросервисов',
        'svg'),
       ('GitLab CI/CD',
        'Пайплайны, 15+ репозиториев, автоматический деплой',
        'svg'),
       ('OAuth2',
        'Единый сервер авторизации для микросервисов',
        'svg'),
       ('Linux',
        'Ubuntu, Debian, Astra Linux — администрирование',
        'svg');

INSERT INTO contacts."user"(user_first_name,
                          user_last_name,
                          user_middle_name,
                          user_phone,
                          user_mail,
                          user_git,
                          user_photo_url)
VALUES ('Андрей',
        'Щербаков',
        'Алексеевич',
        '+7 (916) 027-48-62',
        'andrschkit@gmail.com',
        'https://github.com/andrschkit',
        'https://localhost:8080/userphoto.jpg');

INSERT INTO portfolio.product(product_name,
                              product_description,
                              product_logo_img_url,
                              product_img_url,
                              product_link)
VALUES ('Корпоративный портал УАЗ',
        'Сайт компании: команда 3 человека, 3 месяца, 50+ уникальных пользователей в день',
        'https://localhost:8080/site_logo.jpg',
        'https://localhost:8080/site.jpg',
        'https://uaz-rosatom.ru/'),
       ('Система заявок',
        'Web + Telegram + email: ~70 заявок/мес. без участия 1-й линии поддержки (70% типовых)',
        'https://localhost:8080/supplications_logo.jpg',
        'https://localhost:8080/supplications.jpg',
        'https://uaz-rosatom.ru:13101/'),
       ('Учёт оборудования',
        'Spring Boot + PostgreSQL: еженедельная инвентаризация с 4 часов до 20 минут',
        'https://localhost:8080/inventory_logo.jpg',
        'https://localhost:8080/inventory.jpg',
        'https://uaz-rosatom.ru:13100/'),
       ('Telegram-бот заявок',
        'Создание и отслеживание заявок, связь пользователя с администраторами служб',
        'https://localhost:8080/supplications_tg_logo.jpg',
        'https://localhost:8080/supplications_tg.jpg',
        'https://t.me/UAZ_RA_bot'),
       ('Инфраструктура GitLab + CI/CD',
        'Self-hosted GitLab, Mattermost, OAuth2; автодеплой микросервисов, 15+ репозиториев',
        'https://localhost:8080/alarms_tg_logo.jpg',
        'https://localhost:8080/alarms_tg.jpg',
        'https://github.com/andrschkit'),
       ('Это резюме (Vue + Spring)',
        'Одностраничное резюме: Vue 3, Spring Boot REST API, PostgreSQL, светлая/тёмная тема',
        'https://localhost:8080/site_logo.jpg',
        'https://localhost:8080/site.jpg',
        'https://github.com/andrschkit');
