-- Расширенный набор навыков из резюме

TRUNCATE TABLE
    skills.backend_skills,
    skills.frontend_skills,
    skills.main_skills
RESTART IDENTITY;

INSERT INTO skills.main_skills(main_skills_name,
                               main_skills_description,
                               main_skills_logo)
VALUES ('Управление командами',
        'Отдел до 8 человек: системные администраторы, разработчики, DevOps',
        'svg'),
       ('Agile (Scrum, Kanban)',
        'Управление бэклогом, планирование спринтов и ресурсов',
        'svg'),
       ('KPI и процессы',
        'Постановка KPI, документация сервисов, наставничество',
        'svg'),
       ('Jira / GitLab',
        'Управление проектами, 15+ репозиториев, процессы разработки',
        'svg'),
       ('Docker',
        'docker-compose, контейнеризация и оркестрация микросервисов',
        'svg'),
       ('GitLab CI/CD',
        'Пайплайны автодеплоя: вывод фичи с 2 недель до 3 дней',
        'svg'),
       ('Микросервисная архитектура',
        'Миграция 3 продуктов с монолита: деплой с 1 дня до 1 часа',
        'svg'),
       ('Self-hosting',
        'Mattermost, GitLab, OAuth2 — единая авторизация 5 сервисов',
        'svg'),
       ('Техническое лидерство',
        'От постановки задачи до продакшена: fullstack и инфраструктура',
        'svg');

INSERT INTO skills.frontend_skills(frontend_skills_name,
                                   frontend_skills_description,
                                   frontend_skills_logo)
VALUES ('Vue.js',
        'Pet-проекты и это резюме на Vue 3 + Vite',
        'svg'),
       ('JavaScript',
        'ES6+, REST-клиенты, интерактивные интерфейсы',
        'svg'),
       ('HTML5 / CSS3',
        'Адаптивная вёрстка, корпоративные порталы',
        'svg'),
       ('Bootstrap',
        'Корпоративный портал УАЗ, командная разработка',
        'svg');

INSERT INTO skills.backend_skills(backend_skills_name,
                                  backend_skills_description,
                                  backend_skills_logo)
VALUES ('Java / Spring Boot',
        'REST API, учёт оборудования, бэкенд этого резюме',
        'svg'),
       ('PostgreSQL',
        'Проектирование схем, хранение данных приложений',
        'svg'),
       ('REST API',
        'Проектирование и интеграция микросервисов',
        'svg'),
       ('Docker',
        'Контейнеры, docker-compose, prod- и dev-стенды',
        'svg'),
       ('GitLab CI/CD',
        'Сборка, тесты, автоматический деплой в прод',
        'svg'),
       ('OAuth2',
        'Единый сервер авторизации для микросервисов',
        'svg'),
       ('Linux',
        'Ubuntu, Debian, Astra Linux — администрирование',
        'svg');
